### ISSUE TITLE
Container block: Different "variations"

### ISSUE THREAD

**Issue by strarsis** [ArrayHQ/atomic-blocks#16]
@atomicblocks, @mikemcalister: If the container block can be styled differently by the theme, 
what is the correct approach for allowing the user to select a variation of that container block?
Should the theme somehow add a variation selection field to the block controls?
Assigning CSS classes would be not optimal because the user cannot 
select from a fixed set and there is no clear captioning or preview possible.

**Comment by mikemcalister** [comment]
Hi there, 

Right now, div is the most widely used and safest option for the container without getting too opinionated. Because the container can be used in many contexts, it's hard to pin it to any other tag. Gutenberg core may be working on a container of their own, and perhaps there will be some insight there.
