### ISSUE TITLE
Sharing Icon Conflict with Elementor

### ISSUE THREAD

**Issue by mikesale** [ArrayHQ/atomic-blocks#19]
When I activate the plugin it breaks Elementor Pro's "Share Buttons" icons for social services, but not email or others that are not services.

Before the Atomic Blocks plugin:
<img width="345" alt="screen shot 2018-10-17 at 8 59 09 am" src="https://user-images.githubusercontent.com/2355139/47095895-577b0580-d1eb-11e8-8321-fae3280b3abd.png">

After activating Atomic Blocks:
<img width="366" alt="screen shot 2018-10-17 at 10 46 34 am" src="https://user-images.githubusercontent.com/2355139/47102456-0f171400-d1fa-11e8-9a8f-0ce9a569ef01.png">

To reproduce:
1. Create a page with Elementor Pro "Share Buttons" and confirm they are showing. 
2. Install and activate Atomic Blocks

**Comment by mikemcalister** [comment]
Hi Mike, 

Thanks for the heads up. This is because Elementor is loading an old version of FontAwesome and we're loading the newer version, which is preferred. There have been [many requests](https://github.com/pojome/elementor/issues/4430) for Elementor to upgrade, but they have been silent about the upgrade. Hoping to see some action there soon!

There are some ways to work around it, but they require dequeuing scripts and hoping that the selectors match up. There are a few suggestions in that link.
