### ISSUE TITLE
Button not displaying consistently 

### ISSUE THREAD

**Issue by dartiss** [ArrayHQ/atomic-blocks#33]
To recreate, install the Twenty Nineteen theme, which is part of the WP 5.0 RC. When adding an Atomic Blocks button to a post or page, it displays the button without an underline on the link. However, when displayed on the front-end, the underline has been added.

Although I can't recreate this in other themes, I'm wondering if this is an Atomic Blocks issue, as I would have thought the plugin's own CSS should ensure consistency across back and front end.

If you believe this is a Twenty Nineteen issue, please let me know and I'll report it to the developers of that theme.

Thanks.

**Comment by mikemcalister** [comment]
Hi David, 

I see the underline you're talking about. This isn't exactly a bug, but it does bring up some situations that we'll likely start seeing with Gutenberg, blocks and themes. We've actually removed the underline in our block button, but the theme's specific styles have overridden that, and added it back. You'll probably want to have a place to add CSS tweaks for blocks in situations like this. 

We don't want to be too heavy handed in our approach to styles, because then it makes it hard to customize for users. In fact, we have [another issue ](https://github.com/ArrayHQ/atomic-blocks/issues/38)open now that is talking about that very issue. 

With Atomic Blocks, we'll have to balance providing styles to ensure proper presentation, while also allowing a lot of flexibility for users.
