### ISSUE TITLE
Disable unneeded CSS

### ISSUE THREAD

**Issue by zu** [ArrayHQ/atomic-blocks#41]
Do I really have to overwrite colors and fonts for atomic blocks or is there a way to remove unwanted CSS.

Colors and font-sizes should be defined by the theme and not by a plugin.

I think you're aware of this already as it's similar to [issue38](https://github.com/ArrayHQ/atomic-blocks/issues/38)

**Comment by mikemcalister** [comment]
Hi there, 

It depends on what kind of CSS you want to override. I don't agree that all colors and font-sizes should be defined by the theme. In order to provide a cohesive design system to the blocks, there are some sensible defaults that should be set. Themes load a ton of different styles and there's no way to ensure they will look great or cohesive with the blocks just yet. 

Some of the blocks are being worked on to make overriding them easier, but there will always be a need for some base styles.

**Comment by mindctrl** [comment]
Maybe there's a middle ground here. What if the plugin had a way to prevent its own stylesheet from loading? That could be a `current_theme_supports` thing, or a boolean filter that lets themes turn them off (default being on), or maybe an option in the settings to disable them.

**Comment by mikemcalister** [comment]
That's definitely an option, but it would remove ALL styles from the blocks, leaving them just markup. That could be beneficial in some situations, but would require a good amount of custom CSS to style them again.
